### ISSUE TITLE
classify a batch of samples use Pre-defined reference

### ISSUE THREAD

**Issue by Tim0thy1** [CityUHK-CompBio/DeepCC#10]
Hi,
我有一批bulk RNAseq样品想进行CMS分型分析,看了Quick start,还是有点不懂. 特此请教一下.

在你们online tools上做分析, 不需要用到label信息, 但在Quick start举的例子, 好像必需得给一个label去做trainning. 能直接使用Pre-defined reference去做预测吗?

**Comment by gaofeng21cn** [comment]
你好，

如果是肠癌样本，你可以直接用我们的在线网站，没有必要自己写程序。我们的离线版本，主要是给有CMS分型以外的需求使用，DeepCC本身是一个框架，可以做任意类型的分子分型工作。

>
> Best regards,
> Feng GAO, Ph.D.,
> Associate Professor
> The Sixth Affiliated Hospital, Sun Yat-sen University
> Guangzhou, China
在 2020年8月31日 +0800 15:03，Tim0thy1 <notifications@github.com>，写道：

**Comment by Tim0thy1** [comment]
我的矩阵有点大, online那上传不上去(Maximum upload size exceeded)...  请问是否可以把online上的肠癌的deepcc_model数据,或者构建deepcc_model的数据+代码发我一下呢?

**Comment by Tim0thy1** [comment]
> 你好， 如果是肠癌样本，你可以直接用我们的在线网站，没有必要自己写程序。我们的离线版本，主要是给有CMS分型以外的需求使用，DeepCC本身是一个框架，可以做任意类型的分子分型工作。
> Best regards, Feng GAO, Ph.D., Associate Professor The Sixth Affiliated Hospital, Sun Yat-sen University Guangzhou, China
> 在 2020年8月31日 +0800 15:03，Tim0thy1 <notifications@github.com>，写道：
> […](#)
> Hi, 我有一批bulk RNAseq样品想进行CMS分型分析,看Quick start,还是有点不懂. 特此请教一下. 1. > 如果我自己训练model (需要label), 所以getFunctionalSpectra与train_DeepCC_model是否就要用CRCSC他们TCGA数据集的分型结果? 2. > new_fs_single <- getFunctionalSpectrum(new_ep, refExp = "COADREAD") 这里new_ep是否能支持多样品的矩阵? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我的矩阵有点大, online那上传不上去(Maximum upload size exceeded)... 请问是否可以把online上的肠癌的deepcc_model数据,或者构建deepcc_model的数据+代码发我一下呢?

**Comment by gaofeng21cn** [comment]
可以的，肠癌的DeepCC模型我们可以分享。

**Comment by Tim0thy1** [comment]
> 可以的，肠癌的DeepCC模型我们可以分享。

十分感谢, 那肠癌DeepCC模型,你是准备上传到哪呢?

**Comment by gaofeng21cn** [comment]
已更新，可以参见首页。我们同时提供了baidu云盘和github的下载。希望多使用多引用我们的工作。

**Comment by Tim0thy1** [comment]
感谢!
