### ISSUE TITLE
length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by hmkim** [CityUHK-CompBio/DeepCC#12]
![스크린샷 2020-10-08 오전 11 39 39](https://user-images.githubusercontent.com/4966343/95408696-0970e680-095b-11eb-88bf-0d324cab93a4.png)

Hi!

I would like to solve this issue.

Thank you in advance!

**Comment by zero19970** [comment]
Hi, thanks for using our DeepCC tools. In our defined function "getFunctionalSpectra()", each row of of the param eps, gene expression profiles, presents one sample. So you need first  transpose eps. Also, we recommend to apply logChange to eps with log2(TPM+1) or log2(TPM + 1e-6) before getting functional spectra.

**Comment by zero19970** [comment]
x-special/nautilus-clipboard
copy
file:///home/lee/Pictures/2020-10-08%2012-31-30%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by zero19970** [comment]
![Uploading 2020-10-08 12-31-30屏幕截图.png…]()

**Comment by zero19970** [comment]
![getFunctionSpectra](https://user-images.githubusercontent.com/43749002/95415415-c3b81c00-0962-11eb-871e-3bec6c481404.png)

**Comment by hmkim** [comment]
@zero19970  Thank you!

`eps = log2(t(eps) + 1e-6)`
