### ISSUE TITLE
NA returned by get_DeepCC_label

### ISSUE THREAD

**Issue by ahwanpandey** [CityUHK-CompBio/DeepCC#16]
Hello,

I get about 12 out of 300 samples with NA prediction after running get_DeepCC_label with default parameters. Could you please explain why this happens and if there is a workaround?

Thanks,
Ahwan

**Comment by zero19970** [comment]
Hi Ahwan, 

Prediction with get_DeepCC_label will return the probability of each type. If the probabilities of all types are all lower than 0.5, then the final prediction will be NA.  

Best wish,
Chenghang
