### ISSUE TITLE
Problem installed DeepCC

### ISSUE THREAD

**Issue by amphun** [CityUHK-CompBio/DeepCC#2]
Hi
I got this error while installed DeepCC any suggestions?

devtools::install_github("CityUHK-CompBio/DeepCC")
mxnet     (NA    -> 1.3.0  ) [CRAN]
dplyr     (0.8.4 -> 0.8.5  ) [CRAN]
igraph    (1.1.2 -> 1.2.4.2) [CRAN]
lifecycle (0.1.0 -> 0.2.0  ) [CRAN]
ggplot2   (3.2.1 -> 3.3.0  ) [CRAN]
isoband   (NA    -> 0.2.0  ) [CRAN]
Installing 6 packages: mxnet, dplyr, igraph, lifecycle, ggplot2, isoband
Error: Failed to install 'DeepCC' from GitHub:
  (converted from warning) unable to access index for repository https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/macosx/mavericks/contrib/3.3:
  cannot download all files

Many thanks

**Comment by amphun** [comment]
Here is additional error:
devtools::install_github("CityUHK-CompBio/DeepCC")
Downloading GitHub repo CityUHK-CompBio/DeepCC@master
Skipping 1 packages not available: mxnet
Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'zone/tz/2019c.1.0/zoneinfo/Asia/Bangkok'
ERROR: dependency ‘mxnet’ is not available for package ‘DeepCC’
* removing ‘/Users/amphun/.RLibrary/DeepCC’
Error: Failed to install 'DeepCC' from GitHub:
  (converted from warning) installation of package ‘/var/folders/r9/qb4kx9zx0gz_sp7v7pgrmkrh0000gn/T//RtmpAUdEUr/filec1c42b2bec05/DeepCC_0.3.0.9000.tar.gz’ had non-zero exit status
In addition: Warning message:
In pkgbuild::with_build_tools({ : bytecode version mismatch; using eval

**Comment by gaofeng21cn** [comment]
Hi,

I think it's something wrong with mxnet's prebuilt R package. I checked it today and found they only have a prebuilt R package for Windows/macOS. For Linux or other situation like downloading issue, I think you can manually install it following their guide. https://mxnet.apache.org/get_started?platform=linux&language=r&processor=cpu&

Anyway, we will change the deep learning backend to keras to get better R compatibility.
