### ISSUE TITLE
Extracting information from DeepFeatures

### ISSUE THREAD

**Issue by jebard** [CityUHK-CompBio/DeepCC#9]
How do you link the DeepFeatures to the original msigDB? I have 10 DeepCC Features (feature 4 and 7 look interesting) but I'm unsure how to interpret what this means in a biological sense. Do you have any recommendations for next steps in the analysis?

**Comment by gaofeng21cn** [comment]
Hi Jonathan,

I think there are two ways. The first one is simple. We can calculate the correlation between Functional Spectra and Deep Features, then you can order the results by absolute correlation values. It will be very clear that which are highly correlated pathways from the name.

A fancy way to do the same thing is generating the activation map of the deep network, kind of visualisation of a DL network to show which input can activate the node of certain deep feature but we are still working on it to make it user friendly.

**Comment by jebard** [comment]
Perfect, thank you!
